const sampleData = [
    {
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        language: "English",
        publisher: "J. B. Lippincott & Co.",
        publisher_city: "New York City",
        publication_date: new Date("July 11, 1960"),
        ISBN: 9780061120084,
        coverpage: "https://m.media-amazon.com/images/I/81gepf1eMqL._AC_UF1000,1000_QL80_.jpg",
        review:"good very good",
    },
    {
        title: "1984",
        author: "George Orwell",
        language: "English",
        publisher: "Secker & Warburg",
        publisher_city: "London",
        publication_date: new Date("June 8, 1949"),
        ISBN: 9780451524935,
        coverpage: "https://rukminim2.flixcart.com/image/850/1000/xif0q/book/m/c/5/-original-imagqtdt7tnzf8dk.jpeg?q=90&crop=false",
        review:"good very good",
    },
    {
        title: "The Catcher in the Rye",
        author: "J. D. Salinger",
        language: "English",
        publisher: "Little, Brown and Company",
        publisher_city: "Boston",
        publication_date: new Date("July 16, 1951"),
        ISBN: 9780316769488,
        coverpage: "https://thethinksync.com/wp-content/uploads/2021/09/thecatcherintherye.jpg",
        review:"good very good",
    },
    {
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        language: "English",
        publisher: "Charles Scribner's Sons",
        publisher_city: "New York City",
        publication_date: new Date("April 10, 1925"),
        ISBN: 9780743273565,
        coverpage: "https://m.media-amazon.com/images/I/81QuEGw8VPL._AC_UF1000,1000_QL80_.jpg",
        review:"good very good",
    },
    {
        title: "Moby-Dick",
        author: "Herman Melville",
        language: "English",
        publisher: "Harper & Brothers",
        publisher_city: "New York City",
        publication_date: new Date("October 18, 1851"),
        ISBN: 9780142437249,
        coverpage: "https://m.media-amazon.com/images/M/MV5BYzg0MjFmMjAtMmNlMC00ZmEzLWE0ZDQtYTFhZjAyNzIxZWU3XkEyXkFqcGdeQXVyMjQwMjk0NjI@._V1_.jpg",
        review:"good very good",
    },
    {
        title: "War and Peace",
        author: "Leo Tolstoy",
        language: "Russian",
        publisher: "The Russian Messenger",
        publisher_city: "Moscow",
        publication_date: new Date("1869"),
        ISBN: 9780199232765,
        coverpage: "https://rukminim2.flixcart.com/image/850/1000/kshtxu80/book/t/c/q/war-and-peace-original-imag6fw59eeyhkza.jpeg?q=90&crop=false",
        review:"good very good",
    },
    {
        title: "Crime and Punishment",
        author: "Fyodor Dostoevsky",
        language: "Russian",
        publisher: "The Russian Messenger",
        publisher_city: "St. Petersburg",
        publication_date: new Date("1866"),
        ISBN: 9780140449136,
        coverpage: "https://m.media-amazon.com/images/I/71O2XIytdqL._AC_UF1000,1000_QL80_.jpg",
        review:"good very good",
    },
    {
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        language: "English",
        publisher: "George Allen & Unwin",
        publisher_city: "London",
        publication_date: new Date("September 21, 1937"),
        ISBN: 9780547928227,
        coverpage: "https://m.media-amazon.com/images/M/MV5BMzU0NDY0NDEzNV5BMl5BanBnXkFtZTgwOTIxNDU1MDE@._V1_FMjpg_UX1000_.jpg",
        review:"good very good",
    },
    {
        title: "Anna Karenina",
        author: "Leo Tolstoy",
        language: "Russian",
        publisher: "The Russian Messenger",
        publisher_city: "Moscow",
        publication_date: new Date("1878"),
        ISBN: 9780143035008,
        coverpage: "https://cdn.kobo.com/book-images/f3b573aa-97a4-4ab9-ad00-23dd64690878/1200/1200/False/anna-karenina-64.jpg",
        review:"good very good",
    }
];

module.exports = { data: sampleData };
